GET http://localhost:3000/todos/1717752407789 HTTP/1.1
Host: localhost:3000
Connection: close

###

POST http://localhost:3000/todos HTTP/1.1
Host: localhost:3000
Connection: close
Content-Type: application/json

{
  "title": "Test Todo"
}

###

DELETE http://localhost:3000/todos/1717751540598 HTTP/1.1
Host: localhost:3000
Connection: close